name: 'PHP NoVerify Linter'
description: 'php syntax control (php -l)'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  ignore:
    description: 'Ignore Folder to check syntax'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ignore }}
